version: '3.1'
services:
  postgis:
    image: pgrouting/pgrouting
    container_name: postgis
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ola.pt
      PGADMIN_DEFAULT_PASSWORD: admin
    links:
      - postgis
  geoserver:
    image: geonode/geoserver
    container_name: geoserver
    ports:
      - '8080:8080'
      - '80:80'
    links:
      - postgis
    volumes:
      - ./geoserverdata/data:/geoserver_data/data
networks:
  defaut:
    name: webmaps_network